### ISSUE TITLE
how bout putting it into quicklisp?

### ISSUE THREAD

**Issue by kidd** [k-stz/cl-ptrace#2]
Hi!

I was thinking that it would be super nice to have cl-ptrace available through quicklisp.

What do you think about it?

Btw, your videos are amazing At many levels. Really, if you have more ideas (and time), I totally encourage you to do more of them!!

Cheers!

**Comment by k-stz** [comment]
Hey, that's an exciting idea! 

I'd have to look into what requirements should be met to include it into quicklisp -
the thought never crossed my mind!

Thank you! Another video is coming soon ;)

**Comment by ryukinix** [comment]
I think a better idea it's using [ultralisp] and [quicksys]

[quicksys]: https://github.com/commonlispbr/quicksys
[ultralisp]: https://ultralisp.org

**Comment by ryukinix** [comment]
https://ultralisp.org/projects/k-stz/cl-ptrace

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/54648767-3eba9880-4a86-11e9-8646-0daedcfe4982.png)
![image](https://user-images.githubusercontent.com/7642878/54648771-42e6b600-4a86-11e9-9b2c-65830157b8c5.png)

**Comment by k-stz** [comment]
Hey @ryukinix 
Thanks for the interesting suggestion. It works on my system as well installing through Ultralisp. I'd like to advertise its use, and thus close this issue. But I'm not quite sure if this is the intended use, maybe you can answer these questions:

(1) Does Ultralisp have no requirements for the projects added to it?
(2) Does it keep in sync with this Github version of cl-ptrace?

Cheers!

**Comment by ryukinix** [comment]
> (1) Does Ultralisp have no requirements for the projects added to it?

Minimal requirements: your ASDF system should load it correctly. I think currently the unique restriction is that the .asd file it is on root of the repo.

> (2) Does it keep in sync with this Github version of cl-ptrace?

Yes, it tries to build a new version (if have new commits) with 5 minutes of frequency.

**Comment by ryukinix** [comment]
You can talk to the author here https://gitter.im/40ants/team

It's a russian CL developer called Alexander. It's a nice person. I have been using ultralisp for a while in several personal projects:

+ https://github.com/ryukinix/lisp-inference
+ https://github.com/ryukinix/lisp-chat
+ https://github.com/commonlispbr/quicksys [¹]
+ https://github.com/ryukinix/leraxandria

¹:  in progress to be [added] in quicklisp, to make it easy loading systems on external dists like ultralisp

[added]: https://github.com/quicklisp/quicklisp-projects/issues/1654

**Comment by k-stz** [comment]
This projects fits indeed much better with Ultralisp. I've added some instructions to the README for getting cl-ptrace from the Ultralisp dist. 
Thanks for the quick and helpful reply @ryukinix!

>     * https://github.com/commonlispbr/quicksys [¹]
> ¹: in progress to be [added](https://github.com/quicklisp/quicklisp-projects/issues/1654) in quicklisp, to  
make it easy loading systems on external dists like ultralisp

Hey that's a nice development for the community, simplifying the use even more! I should point this out in the README once it's added to quicklisp!

The issue now can be closed in good faith.
