### ISSUE TITLE
Why to use PTRACE_SINGLESTEP  before PTRACE_GETREGS ?

### ISSUE THREAD

**Issue by hjr72305** [k-stz/cl-ptrace#5]
You can get registers with PTRACE_GETREGS  before you do the first PTRACE_SINGLESTEP

**Comment by k-stz** [comment]
Hello,
you must be talking about the SINGLESTEP function. The %GETREGS call inside it doesn't seem to serve a purpose, as the `regs' variable isn't used. Must be some old code that should be safe to remove now.

I'll have to test it carefully.

**Comment by k-stz** [comment]
removed the code with the latest commit https://github.com/k-stz/cl-ptrace/commit/ee490b495904c6ea6d8d7ad72d1bc11c02f4280d

thank you
